config/routes.rb
Rails.application.routes.draw do

  root to: 'pages#home'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  resources :keywords #, only:[:new, :create, :index, :show]
    
    # # Read action routes
    # get "/keywords" => "keywords#index"
    # get "/keywords/:id" => "keywords#show"
    
    # # Create action routes
    # get "/keywords/new" => "keywords#new"
    # post "/keywords" => "keywords#create"

    # # Update action routes
    # get "/keywords/:id/edit" => "keywords#edit"
    # patch "/keywords/:id" => "keywords#update"
  
    # # Delete action routes
    # delete "/keywords/:id/delete" => "keywords#destroy"
    
  end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/keyword.rb
class Keyword < ApplicationRecord
    
    validates :name, presence: true, uniqueness: true
    
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/keywords_controller.rb
class KeywordsController < ApplicationController
    
    before_action :find_keyword, only:[:show, :edit, :update, :destroy]
    
    def index
        @keywords = Keyword.all
    end
    
    def show
    end
    
    def new
        @keyword = Keyword.new
    end
    
    def create
        @keyword = Keyword.new(keyword_params)
        if @keyword.save
            redirect_to keywords_path
        else    
            render :new
        end
        
    end
    
    def edit
    end
    
    def update
        if @keyword.update(keyword_params)
            redirect_to keywords_path
        else
            render :edit
        end
    end
    
    def destroy
        @keyword.destroy
        redirect_to keywords_path
    end

    private 
    
    def keyword_params
        params.require(:keyword).permit(:name)
    end
    
    def find_keyword
        @keyword = Keyword.find(params[:id])

    end
    
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
     @keyword = Keyword.new
    
  end
end

app/controllers/websites_controller.rb
class WebsitesController < ApplicationController
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/keywords_helper.rb
module KeywordsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/websites_helper.rb
module WebsitesHelper
end

app/views/keywords/_form.html.erb
  <%= simple_form_for @keyword do |k| %>
   <%= k.input:name, placeholder:"Keyword", label:"Mot clé" %>
   <%= k.button:submit,value:"Ajouter",class:"btn btn-primary" %>
   <% end %>
         

app/views/keywords/edit.html.erb
<div class="container">
    <div class="row">
        <h1 class="text-center">Ajouter un mot clé</h1>
        <div class="col-xs-12 col-sm-6 col-sm-offset-3">
           
            <%= render "form" %>
         
        </div>
    </div>
</div>

app/views/keywords/index.html.erb
<div class="container text-center">

    <h1>Nos mots clefs</h1>
    <ul>
        <% @keywords.each do |keyword|%>
        <li><%= link_to keyword.name, keyword_path(keyword) %>
        <%= link_to "Supprimer", keyword_path(keyword), method: :delete %>
        </li>
        <% end %>
    </ul>
    
    <p>
        <%= link_to "Revenir à l'accueil", root_path %>
    </p>
    
</div>

app/views/keywords/new.html.erb
<div class="container">
    <div class="row">
        <h1 class="text-center">Ajouter un mot clé</h1>
        <div class="col-xs-12 col-sm-6 col-sm-offset-3">
            <%= render "form" %>
        </div>
    </div>
    
</div>

app/views/keywords/show.html.erb
<div class="container text-center">

    <h1><%=@keyword.name %></h1>

    <p>
        <%= link_to "Revenir à la liste", keywords_path %>
    </p>
    
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <title>Keyworth | Etude de la concurrence organique de vos mots clés</title>
    <%= csrf_meta_tags %>
    <%= action_cable_meta_tag %>
    <%= stylesheet_link_tag    'application', media: 'all' %>
  </head>
  <body>
    <%= render "shared/navbar" %>
    <%= yield %>
    <%= javascript_include_tag 'application' %>
  </body>
</html>

app/views/pages/home.html.erb
<div class="banner" style="background-image: linear-gradient(-225deg, rgba(0,101,168,0.6) 0%, rgba(0,36,61,0.6) 50%), url('background.jpg');">
    <div class="banner-content">
        <h1>Keyworth</h1></h1>
        <h2>Est-ce que vos efforts SEO ont un véritable ROI ? </h2>
            <%= simple_form_for @keyword, :html=> { class: 'navbar-wagon-search' } do |k| %>
            <%= k.input:name, placeholder:"Calculer la concurrence organique",class:"navbar-wagon-search-input", label:false  %>
            <%= k.button :button,class:"navbar-wagon-search-btn"  do %>
                <i class="fa fa-search"></i>-->
            <% end %>
            <% end %>
    </div>  
</div>

app/views/shared/_navbar.html.erb
<div class="navbar-wagon">
  <!-- Logo -->
  <%= link_to "KeyWorth", root_path, class:"logo-title"  %>

  <!-- Right Navigation -->
  <div class="navbar-wagon-right hidden-xs hidden-sm">

    <!-- Text link -->
    <a href="" class="navbar-wagon-item navbar-wagon-link">Contact</a>

    <!-- Profile picture and dropdown -->
    <div class="navbar-wagon-item">
      <div class="dropdown">
        <img src="http://placehold.it/50x50" class="avatar dropdown-toggle" id="navbar-wagon-menu" data-toggle="dropdown">
        <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
          <li><a href="#">Profile</a></li>
          <li><a href="#">Dashboard</a></li>
          <li><a href="#">Log Out</a></li>
        </ul>
      </div>
    </div>
  </div>

  <!-- Dropdown appearing on mobile only -->
  <div class="navbar-wagon-item hidden-md hidden-lg">
    <div class="dropdown">
      <i class="fa fa-bars dropdown-toggle" data-toggle="dropdown"></i>
      <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
        <li><a href="#">Contact</a></li>
      </ul>
    </div>
  </div>
</div>